version = 0.1

[default.build.parameters]
cached = true
parallel = true

[default.deploy.parameters]
stack_name = "halloweenready-dev"
resolve_s3 = true
s3_prefix = "halloweenready"
region = "us-east-1"
capabilities = "CAPABILITY_IAM"
parameter_overrides = "Environment=dev"
confirm_changeset = true

[staging.deploy.parameters]
stack_name = "halloweenready-staging"
resolve_s3 = true
s3_prefix = "halloweenready"
region = "us-east-1"
capabilities = "CAPABILITY_IAM"
parameter_overrides = "Environment=staging LoadTestMode=true"

[prod.build.parameters]
cached = true
parallel = true

[prod.deploy.parameters]
stack_name = "halloweenready-prod"
resolve_s3 = true
s3_prefix = "halloweenready"
region = "us-east-1"
capabilities = "CAPABILITY_IAM"
parameter_overrides = "Environment=prod"
confirm_changeset = true
